GLOBAL_OBSTACLE_CATEGORY_MAPPING = {
    "建筑物/构建物": "building_general",
    "高压架空输电线路（35kV以下）":       "power_line_high_voltage_35kv_below",
    "高压架空输电线路（35kV）":          "power_line_high_voltage_35kv",
    "高压架空输电线路（110kV）":         "power_line_high_voltage_110kv",
    "高压架空输电线路（220kV）":         "power_line_high_voltage_220kv",
    "高压架空输电线路（330kV）":         "power_line_high_voltage_330kv",
    "高压架空输电线路（500kV及以上）":    "power_line_high_voltage_500kv_and_above",
    "风力涡轮发电机等大型旋转反射物体": "large_rotating_reflector",
    "机库": "building_hangar",
    "航站楼": "building_terminal",
    "电气化铁路": "railway_electrified",
    "非电气化铁路": "railway_non_electrified",
    "道路/公路": "road",
    "山丘": "hill",
    "堤坝": "embankment",
    "铁塔/高塔": "tower",
    "树木/树林": "tree_or_forest",
    "金属围栏/金属栅栏": "metal_fence",
    "电力线缆和通信线缆": "power_or_communication_cable",
    "车辆/航空器/机械": "vehicle_or_aircraft_or_machine",
    "架空低压电力线": "power_line_low_voltage_overhead",
    "机场专用环场路": "airport_ring_road",
    "中波和长波发射台（小于50kW）": "radio_emitter_medium_long_wave_50kw_below",
    "中波和长波发射台（100-150kW）": "radio_emitter_medium_long_wave_100_to_150kw",
    "中波和长波发射台（大于200kW）": "radio_emitter_medium_long_wave_above_200kw",
    "短波发射台（通信方向1/4功率角 0.5-5kW）": "radio_emitter_short_wave_quarter_power_angle_0_5_to_5kw",
    "短波发射台（通信方向1/4功率角 5-25kW）": "radio_emitter_short_wave_quarter_power_angle_5_to_25kw",
    "短波发射台（通信方向1/4功率角 25-120kW）": "radio_emitter_short_wave_quarter_power_angle_25_to_120kw",
    "短波发射台（通信方向1/4功率角 >120kW）": "radio_emitter_short_wave_quarter_power_angle_above_120kw",
    "短波发射台（通信方向1/4功率角外 0.5-5kW）": "radio_emitter_short_wave_outside_quarter_power_angle_0_5_to_5kw",
    "短波发射台（通信方向1/4功率角外 5-25kW）": "radio_emitter_short_wave_outside_quarter_power_angle_5_to_25kw",
    "短波发射台（通信方向1/4功率角外 25-120kW）": "radio_emitter_short_wave_outside_quarter_power_angle_25_to_120kw",
    "短波发射台（通信方向1/4功率角外 >120kW）": "radio_emitter_short_wave_outside_quarter_power_angle_above_120kw",
    "短波发射台（其他）": "radio_emitter_short_wave_other",
    "工、科、医射频设备": "industrial_scientific_medical_rf_equipment",
    "调频广播1kW（含）以下": "fm_broadcast_1kw_below",
    "调频广播1kW以上": "fm_broadcast_above_1kw",
    "高压变电站（110kV）": "high_voltage_substation_110kv",
    "高压变电站（220-330kV）": "high_voltage_substation_220kv_or_330kv",
    "高压变电站（500kV及以上）": "high_voltage_substation_500kv_and_above",
    "高压变电站（其他）": "high_voltage_substation_other",
    "高频热合机": "high_frequency_welding_machine",
    "高频炉（100kW及以下）": "high_frequency_furnace_100kw_below",
    "高频炉（100kW以上）": "high_frequency_furnace_above_100kw",
    "工业电焊（10kW及以下）": "industrial_electric_welding_10kw_below",
    "工业电焊（10kW以上）": "industrial_electric_welding_above_10kw",
    "超高频理疗机（1kW及以下）": "uhf_therapy_equipment_1kw_below",
    "超高频理疗机（1kW以上）": "uhf_therapy_equipment_above_1kw",
    "农用电力设备（1kW及以下）": "agricultural_power_equipment_1kw_below",
    "农用电力设备（1kW以上）": "agricultural_power_equipment_above_1kw",
    "有无线电辐射的工业设施": "industrial_radio_radiation_facility",
    "气象雷达站": "weather_radar_station",
}


# 将原始障碍物类型归一化为全局分类编码。
def normalize_obstacle_type(raw_type: str | None) -> str:
    if raw_type is None:
        return "unclassified"

    return GLOBAL_OBSTACLE_CATEGORY_MAPPING.get(raw_type, "unclassified")
